################################################################################
##  validation/v7_check_pffc_generator.R
##
##  Does generate_pffc() produce progressively first-failure-censored samples?
##
##  Every simulated number in this paper rests on one function, and that
##  function does not simulate the experiment.  It uses the equivalence noted by
##  Wu and Kus (2009, Section 2): the progressively first-failure-censored order
##  statistics from a population with distribution function F are distributed as
##  a progressively type-II censored sample from the population with
##  distribution function
##
##      F_k(x) = 1 - (1 - F(x))^k ,
##
##  which for the GIE distribution is again GIE, with the shape multiplied by k,
##  since 1 - F(x) = (1 - e^{-lambda/x})^alpha.  The type-II sample is then
##  generated by the exponential-spacings form of the algorithm of Balakrishnan
##  and Sandhu (1995).  Both steps are standard, but between them they replace
##  the physical experiment entirely, so an error in either would be invisible:
##  the output would still look like an ordered sample of the right length.
##
##  This script therefore simulates the experiment itself -- n groups of k
##  units, the group containing each failure withdrawn along with R_i further
##  groups drawn at random -- and compares the two, coordinate by coordinate,
##  with a two-sample Kolmogorov-Smirnov test.  The physical version is slow and
##  is used only here; it is the ground truth against which the fast version is
##  checked.
##
##  Two further checks are made, because a Kolmogorov-Smirnov comparison of two
##  simulations can only detect what both do not do:
##
##    * the marginal law of the first failure is known in closed form, since
##      X_1 is the minimum of n independent group minima, so
##      P(X_1 > x) = (1 - F_k(x))^n = S(x)^{alpha k n};
##    * the denominators the generator uses are checked against the number of
##      groups still on test, counted by bookkeeping rather than by the closed
##      form.  These are the factors of the normalising constant of Eq. (2) of
##      Wu and Kus, c = n (n - R_1 - 1) ... (n - R_1 - ... - R_{m-1} - m + 1),
##      and the count must reach exactly zero at the m-th failure.
##
##  The four special cases that paper lists -- R = 0, k = 1, both, and
##  k = 1 with R = (0, ..., 0, n - m) -- are checked at the end.  They are the
##  complete sample, first-failure censoring, progressive type-II censoring and
##  ordinary type-II censoring, and the general code must produce all four
##  without being told about them.
##
##  Runtime: one to two minutes.
################################################################################

source("../00_gie_pffc.R")

set.seed(MASTER_SEED + 107L)

N_FAST <- 20000    # replications from generate_pffc()
N_SLOW <- 3000     # replications from the physical experiment
ALPHA_KS <- 0.001  # per-coordinate significance; see the note below

## ---------------------------------------------------------------------------
## The experiment itself
## ---------------------------------------------------------------------------

#' One progressively first-failure-censored sample, obtained by running the
#' life test rather than by transforming uniforms.
pffc_by_experiment <- function(m, k, R, alpha, lambda) {
  n <- sum(R) + m
  ## n groups of k units; a group fails when its first unit does
  gmin <- apply(matrix(gie_quantile(runif(n * k), alpha, lambda), nrow = k),
                2, min)
  alive <- seq_len(n)
  x <- numeric(m)
  for (i in seq_len(m)) {
    j     <- alive[which.min(gmin[alive])]
    x[i]  <- gmin[j]
    alive <- setdiff(alive, j)
    if (R[i] > 0)
      alive <- setdiff(alive, if (length(alive) == R[i]) alive
                              else sample(alive, R[i]))
  }
  stopifnot(length(alive) == 0L)
  x
}

## ---------------------------------------------------------------------------
## Designs: the four schemes of Section 5.1, a heavy-tailed case, and the
## design of the first application.
## ---------------------------------------------------------------------------
## The last entry is the design of the first application, read from the macro
## file that 10_realdata1_ballbearings.R writes.  Its censoring plan is not one
## of the four named schemes, so it carries its own R.
app <- read_macros(file.path(TABLES_DIR, "values_realdata1.tex"))
designs <- list(
  list(m = 25, k = 2, sch = "Early",  alpha = 5, lambda = 2),
  list(m = 25, k = 5, sch = "Late",   alpha = 5, lambda = 2),
  list(m = 12, k = 3, sch = "Middle", alpha = 2, lambda = 2),
  list(m = 12, k = 2, sch = "Equal",  alpha = 1, lambda = 2),
  list(m = as.numeric(app$bbM), k = as.numeric(app$bbK), sch = "app",
       alpha = as.numeric(app$bbAlphaHat), lambda = as.numeric(app$bbLambdaHat),
       R = c(as.numeric(app$bbRfirst), rep(0, as.numeric(app$bbM) - 1)))
)

fails <- character(0)
chk <- function(cond, msg) if (!isTRUE(cond)) fails <<- c(fails, msg)

for (d in designs) {
  R <- if (is.null(d$R)) make_scheme(d$m, d$sch) else d$R
  n <- sum(R) + d$m

  ## ------------------------------------------------------------------ (a)
  ## the denominators the generator uses must be the factors of Eq. (2)
  cumR  <- c(0, cumsum(R)[-d$m])
  denom <- n - cumR - seq_len(d$m) + 1
  ## The same quantity obtained by bookkeeping rather than by the closed form:
  ## start with n groups and, after each failure, remove that group and R_i more.
  wk_c <- numeric(d$m); left <- n
  for (j in seq_len(d$m)) { wk_c[j] <- left; left <- left - 1 - R[j] }
  chk(isTRUE(all.equal(denom, wk_c)) && left == 0,
      sprintf("%s: generator denominators do not count the groups on test",
              d$sch))
  chk(all(denom > 0) && denom[d$m] >= 1,
      sprintf("%s: a non-positive number of groups on test", d$sch))

  ## ------------------------------------------------------------------ (b)
  ## fast generator versus the experiment
  A <- matrix(NA_real_, N_FAST, d$m)
  for (i in seq_len(N_FAST))
    A[i, ] <- generate_pffc(d$m, d$k, R, d$alpha, d$lambda)
  B <- matrix(NA_real_, N_SLOW, d$m)
  for (i in seq_len(N_SLOW))
    B[i, ] <- pffc_by_experiment(d$m, d$k, R, d$alpha, d$lambda)

  chk(all(A == t(apply(A, 1, sort))), sprintf("%s: generator output not ordered", d$sch))

  p <- vapply(seq_len(d$m),
              function(j) suppressWarnings(ks.test(A[, j], B[, j])$p.value),
              0)
  ## With m coordinates the smallest p-value is small by construction even when
  ## the two agree, so the test is applied at a stringent per-coordinate level
  ## and the p-values are additionally checked for uniformity, which is what
  ## they must be if the two generators agree.
  p_unif <- suppressWarnings(ks.test(p, "punif")$p.value)

  ## ------------------------------------------------------------------ (c)
  ## the closed-form marginal of the first failure
  q  <- quantile(A[, 1], c(0.1, 0.25, 0.5, 0.75, 0.9))
  ## P(X_1 <= x) = 1 - S_k(x)^n, S_k(x) = (1 - e^{-lambda/x})^{alpha k}
  Fx <- 1 - exp(d$alpha * d$k * n * log1p(-exp(-d$lambda / q)))
  emp <- vapply(q, function(z) mean(A[, 1] <= z), 0)
  worst <- max(abs(emp - Fx))

  cat(sprintf("%-7s m=%3d k=%d alpha=%-7g : min KS p = %.4f (%d of %d < %.3f),",
              d$sch, d$m, d$k, d$alpha, min(p), sum(p < ALPHA_KS), d$m, ALPHA_KS))
  cat(sprintf("  uniformity p = %.3f,  |F_hat - F| <= %.4f\n", p_unif, worst))

  chk(min(p) > ALPHA_KS,
      sprintf("%s m=%d k=%d: generator and experiment differ at coordinate %d (KS p = %.5f)",
              d$sch, d$m, d$k, which.min(p), min(p)))
  chk(p_unif > 0.001,
      sprintf("%s m=%d k=%d: KS p-values are not uniform (p = %.4f), so the two disagree systematically",
              d$sch, d$m, d$k, p_unif))
  chk(worst < 0.01,
      sprintf("%s m=%d k=%d: first-failure marginal is off by %.4f from its closed form",
              d$sch, d$m, d$k, worst))
}

## ---------------------------------------------------------------------------
## (d)  The special cases named by Wu and Kus, which the generator must
##      reproduce without being told about them.
## ---------------------------------------------------------------------------
cat("\nSpecial cases:\n")

## k = 1 and R = 0: the complete sample of size m.  The order statistics of a
## complete GIE sample must come out.
m0 <- 30; R0 <- rep(0, m0)
A0 <- replicate(20000, generate_pffc(m0, 1, R0, 3, 2))
q0 <- quantile(as.numeric(A0), c(0.25, 0.5, 0.75))
F0 <- 1 - exp(3 * log1p(-exp(-2 / q0)))
cat(sprintf("  k=1, R=0 (complete sample): max |F_hat - F| = %.4f\n",
            max(abs(c(0.25, 0.5, 0.75) - F0))))
chk(max(abs(c(0.25, 0.5, 0.75) - F0)) < 0.01,
    "k=1 with no censoring does not reproduce the complete sample")

## R = (0,...,0) with k > 1: a first-failure-censored sample, i.e. a complete
## sample of size m from F_k.
A1 <- replicate(20000, generate_pffc(m0, 4, R0, 3, 2))
q1 <- quantile(as.numeric(A1), c(0.25, 0.5, 0.75))
F1 <- 1 - exp(3 * 4 * log1p(-exp(-2 / q1)))
cat(sprintf("  R=0, k=4 (first-failure censoring): max |F_hat - F| = %.4f\n",
            max(abs(c(0.25, 0.5, 0.75) - F1))))
chk(max(abs(c(0.25, 0.5, 0.75) - F1)) < 0.01,
    "R = 0 with k > 1 does not reproduce a complete sample from F_k")

## k = 1, R = (0,...,0,n-m): conventional type-II right censoring, so the sample
## is the first m order statistics of a complete sample of size n.
mt <- 15; nt <- 40; Rt <- c(rep(0, mt - 1), nt - mt)
At <- replicate(20000, generate_pffc(mt, 1, Rt, 3, 2))
full <- replicate(20000, sort(gie_quantile(runif(nt), 3, 2))[seq_len(mt)])
pt <- vapply(seq_len(mt),
             function(j) suppressWarnings(ks.test(At[j, ], full[j, ])$p.value), 0)
cat(sprintf("  k=1, R=(0,...,0,n-m) (type-II censoring): min KS p = %.4f\n", min(pt)))
chk(min(pt) > ALPHA_KS,
    sprintf("k=1 with R=(0,...,0,n-m) does not reproduce type-II censoring (KS p = %.5f)",
            min(pt)))

## ---------------------------------------------------------------------------
cat("\n")
if (length(fails) == 0) {
  cat("PASS: generate_pffc() agrees with the experiment it stands for.  The\n",
      "equivalence of Wu and Kus (2009) and the algorithm of Balakrishnan and\n",
      "Sandhu (1995) are correctly implemented, the first-failure marginal\n",
      "matches its closed form, and the four special cases named in that paper\n",
      "-- complete sample, first-failure censoring, progressive type-II\n",
      "censoring and ordinary type-II censoring -- all come out of the general\n",
      "code without being special-cased.\n", sep = "")
} else {
  for (f in fails) cat("  - ", f, "\n", sep = "")
  stop("FAIL: the PFFC generator does not reproduce the experiment.")
}
